// BACKEND NOTE
// WHAT IS BACKEND?
//  THIS REFERS TO THE PART OF THE WEBSITE THAT OPERATES ON THE SERVER SIDE, BEHIND THE SCENES.
// RESPONSIBLE FOR MANAGING AND PROCESSING THE DATA, HANDLING BUSINESS LOGIC AND PERFORMING TASKS THE FRONTEND CANNOT HANDLE.
// WHAT DO WE USE BACKEND TO DO?
// 1.SERVER: THE BACKEND RUNS ON A SERVER, WHICH CAN BE A SINGLE COMPUTER /LAPTOP, A CLUSTER OF COMPUTERS OR SUPER COMPUTERS WHICH HOUSES THE WEBSITE/WEB APPLICATION 
// 2.DATABASE: THE BACKEND INTERACTS WITH THE DATABASE TO STORE AND RETRIEVES DATA. THIS INCLUDES USER INFORMATION, CONTENTS AND OTHER DATA NECESSSARY FOR THE WEBSITE FUNCTIIONALITY. (MONGODB)
// 3.SERVERSIDE PROGRAMMING LANGUAGES: JAVASCRIPT/TYPESCRIPT(NODE/{FRAMEWORK EXPRESS}), PYTHON(DJANGO, FLASK), RUBY(RUBY ON RAILS PHP(LARAVEL)) ETC.
// 4. API: (APPLICATION PROGRAMMING INTERFACE) THE BACKEND CAN EXPOSE APIS THAT FRONTEND USES TO REQUEST AND SEND DATA.
// 5. AUTHENTICATION AND AUTHORIZATION: THE BACKEND MANAGES USERS AUTHENTICATION (VERIFYING USER IDENTITY) AND AUTHORIZATION (GRANTING ACCESS TO RESOURCES BASED ON PERMISSION).
// SECURITY: THE BACKEND IMPLEMENTS SECURITY MEASURES TO PROTECT DATA AND ENSURES THAT THE APPLICATION IS SAFE FROM VULNEABILITIES AND ATTACKS.


// TOOLS USED FOR BANKEND DEVELOPMENT
// 1. VS CODE (CODE EDITOR) FOR WRITING AND MANAGING CODE
// 2. DATABWASE: POSTGRES, NYSQL, MOONGODB, NOSQL, FIREBASE ETC.
// 3. LANGUAGES: NODE ........EXPRESS.
// 4. TESTERS: POSTMAN


// REQUEST AND RESPONSE 
// REQUEST: 5 TYPES OF REQUEST
// 1. POST REQUEST: USERS SENDING THEIR INFORMATION TO A SERVER E.G LOGIN, SING-UP, INPUTS ETC. 
// 2. GET REQUEST: RETRIEVING DATA FROM THE SERVER/DATABASE E.G FETCHING USER PROFILE, TASKS ETC.
// 3. DELETE REQUEST: LOG-OUT, DELETE ACCOUNT, DELETE A POST ETC.
// 4. PATCH REQUEST: TO EDIT A DATA THAT HAS ALREADY BEEN POSTED 
// 5. PUT REQUEST: TO UPDATE A DATA THAT HAS ALREADY BEEN POSTED (REPLACE THE ENTIRE DATA WITH NEW DATA)

// RESPONSE:
// 1. GOOD RESPONSE:
// 2. BAD RESPONSE:
// 3. STATUS CODE:

// BACKEND FLOW
// STEP 1: APP.TS,INDEX.TS, MAIN.TS: THIS IS WHRE YOU RUN YOUR SEVER AND CONNECT YOUR DATABASE
// STEP 2: YOU CRAETE A MODEL FOLDER: THIS IS FOR DEFINING THE STRUCTURE OF THE DATA THAT WILL BE STORED IN YOUR DATABASE
// STEP 3: YOU CREATE A CONTROLLER FOLDER: THIS IS WHERE THE BUSINESS LOGIC HAPPENS BETWEEN REQUEST AND RESPONSE
// STEP 4: YOU CREATE THE ROUTES FOLDER: THIS IS WHERE YOU DEFINE YOUR REQUEST ROUTE
//  STEP 5: YOU BRING EVERYTHING BACK TO YOUR SERVER FILE
// STEP 6: OTHER FOLDERS YOU MIGHT CREATE DEPENDING OF THE SCALE OF THE PROJECTS: UTILS FOLDER(UTILITIES), MIDDLEWARE FOLDER ETC.

// npm i --save dev @types/node
// npm i --save dev @types/express